language: csharp
solution: ceilidh-core.sln
mono: none
dotnet: 2.1.302
os:
  - linux
  - osx
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test ProjectCeilidh.Cobble.Tests/ProjectCeilidh.Cobble.Tests.csproj